### PR TITLE
Support variable substitutions

### LINKED ISSUE #4: Support variable substitution
To eliminate the duplications, it would be good to have the variable substitution supported as stated in 
https://github.com/bkeepers/dotenv#variable-substitution

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #4

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Hey @apiraino , what do you think about the feature?

I would love to have it since it allows me to unite configs for diesel and postgres docker image:

```
# library/postgres Docker image requires those parameters to create a database
POSTGRES_USER=image_storage_admin
POSTGRES_PASSWORD=image_storage_password
POSTGRES_DB=image_storage

# Diesel's `PgConnection` requires a database url to be specified
DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"
```

**Comment by apiraino** [comment]
Hi @SomeoneToIgnore thank you so much for contributing with a PR, sorry for the slow answer.
Your suggestion makes a lot of sense, I'd be happy to merge it when you think you're done here

**Comment by SomeoneToIgnore** [comment]
Great!
I think I am done unless you have some feedback :)

Would be great to see it in a new release.

**Comment by apiraino** [comment]
This week I'll have a brief look (I'm spotty these days), then we can merge.

Concerning an official release on `crates.io`, there are still an [open issue](https://github.com/apiraino/rust-dotenv/pull/1#issuecomment-473098234) on that. We might push again and see if we can solve that, too.

**Comment by apiraino** [comment]
Impressive (and long due) set of tests, great job!

**Pull request merged**
